RecommendationSystem/RecommendationSystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('', include("recommendationapp.urls")),
    path('profile/', include('profileapp.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

RecommendationSystem/accounts/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

RecommendationSystem/profileapp/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.profile_view, name='profile'),    
    path('edit', views.edit_profile, name='edit_profile'),    
]

RecommendationSystem/recommendationapp/urls.py
from os import name
from django.urls import path, include
from . import views
urlpatterns = [
    path("", views.index, name='home'),
    path("about/", views.aboutUs),
    path("allpackages/", views.allpackages),
    path("aboutus/", views.aboutUs),
    path("choseoptions/", views.choseoptions),
    path("choseoptions/don't-know-my-requirements/", views.dontknowmyrequirements),
    path("choseoptions/know-my-requirements/", views.knowmyrequirements),
]

RecommendationSystem/accounts/models.py
from django.db import models

# Create your models here.

RecommendationSystem/profileapp/models.py
from distutils.command.upload import upload
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_picture = models.ImageField(default='images/default.jpeg', upload_to='images/', null=True, blank=True)
    first_name = models.CharField(max_length=100, null=True, blank=True)
    last_name = models.CharField(max_length=100, null=True, blank=True)
    gender = models.CharField(max_length=100, null=True, blank=True)
    age = models.PositiveSmallIntegerField(null=True, blank=True)
    
    

    def __str__(self):
        return self.user.username

RecommendationSystem/recommendationapp/models.py
from django.db import models

# Create your models here.

RecommendationSystem/accounts/views.py
import email
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User
# Create your views here.
from profileapp.models import Profile
# accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            return render(request, 'accounts/login.html', {'username':username, 'password':password, 'error': True})
    else:
        return render(request, 'accounts/login.html')

def signup_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password1 = request.POST['password1']      
        password2 = request.POST['password2']
        if password1 == password2:
            user = User.objects.filter(username=username).first()
            if user is not None:
                return render(request, 'accounts/signup.html', {'username':username, 'password':password1, 'error1': 'Username already exists'})
            else:
                user = User.objects.create_user(username, '', password1)
                try:
                    profile = Profile()
                    profile.user = user
                    profile.save()
                except Exception as e:
                    user.delete()
                    print(e)
                    return redirect('home')
                login(request, user)
                return redirect('home')
        
        else:
            return render(request, 'accounts/signup.html', {'username':username, 'error2': "Passwords didn't matched"})
    else:
        return render(request, 'accounts/signup.html')

def logout_view(request):
    logout(request)
    return redirect('home')

RecommendationSystem/profileapp/views.py
from threading import _profile_hook
from django.shortcuts import render
from .models import Profile
# Create your views here.

def profile_view(request):
    user = request.user
    profile = Profile.objects.filter(user=user).first()
    #print(help(profile))
    return render(request, 'profileapp/profile.html', {'profile':profile})

def edit_profile(request):
    user = request.user
    profile = Profile.objects.filter(user=user).first()
    if request.method == 'POST':
        first_name = request.POST["first_name"]
        last_name = request.POST["last_name"]
        gender = request.POST["gender"]
        age = request.POST["age"]
        if "image" in request.FILES:
            profile.profile_picture = request.FILES["image"]
        
        profile.first_name = first_name
        profile.last_name = last_name
        profile.gender = gender
        profile.age = int(age)
        profile.save()
        return render(request, 'profileapp/profile.html', {'profile':profile})
    else:
        return render(request, 'profileapp/edit_profile.html', {'profile':profile})

RecommendationSystem/recommendationapp/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .aiengine import prediction, prediction2
from .packages import packages, packages_with_details
# Create your views here.

packages = packages
processor_names = ["Custom Intel Xeon E5-2076 v3 Haswell", "AWS Nitro System Xeon", "Intel Xeon Pentium 8176M"]
storage_type_names = ["EBS", "NVMe SSD", "HDD"]

def index(request):
    return render(request, "recommendationapp/recommendationapp.html")

def aboutUs(request):
    return render(request, "recommendationapp/aboutus.html")

def allpackages(request):
    return render(request, "recommendationapp/allpackages.html", {"database":packages_with_details})

def choseoptions(request):
    return render(request, "recommendationapp/choseoptions.html")

def dontknowmyrequirements(request):
    if request.method == "POST":
        company_size = request.POST["company_size"]
        hits = request.POST["hits"]
        package_number = prediction2(company_size, hits)
        package = packages_with_details[package_number]
        return render(request, "recommendationapp/dontknowreply.html", {"package_details": package})
    return render(request, "recommendationapp/dontknowmyrequirements.html")

def knowmyrequirements(request):
    if request.method == "POST":
        vcpu = request.POST["vcpu"]
        ram = request.POST["ram"]
        storage_type = request.POST["storage_type"]
        storage_amount = request.POST["storage_amount"]
        network_bandwidth = request.POST["network_bandwidth"]
        processor = request.POST["processor"]
        package_number = prediction(vcpu, ram, storage_type, storage_amount, network_bandwidth, processor)
        package = packages_with_details[package_number]
        return render(request, "recommendationapp/knowreply.html", {"package_details": package})
    return render(request, "recommendationapp/knowmyrequirements.html")

RecommendationSystem/accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load static %}

{% block page_title %}
    Login
{% endblock %}

{% block other_css_link %}
    <link rel="stylesheet" href="{% static "accounts/login.css" %}?{% now "U" %}">
{% endblock %}

{% block page_content %}
    <div class="container">
        <h3>Login</h3>
        <form action="/accounts/login/" class="form" method="post">
            {% csrf_token %}
            <label for="id_username" class="username">Username</label>
            <input required id="id_username" name="username" type="text" value={{username}} > <br>
            {% if error %}
                <h4 class='cred'> Credentials didn't matched ! </h4>
            {% endif %}
            <label for="id_password" class="password" >Password </label>
            <input required id="id_password" name="password" type="password" value={{password}} > <br>
            <button type="submit">Submit</button>
            <span>Haven't created one? <a href="/accounts/signup">Create One</a> </span>
        </form>
    </div>

{% endblock %}

RecommendationSystem/accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% load static %}
{% block page_title %}
    Create an account
{% endblock %}

{% block other_css_link %}
    <link rel="stylesheet" href="{% static "accounts/signup.css" %}?{% now "U" %}">
{%endblock%}

{% block page_content %}
<div class="container">
    <h3>Create Account</h3>
    <form action="" class="form" method="POST">
        {% csrf_token %}
        <input type="text" name="username" placeholder="Username" value={{username}}> <br>
        {% if error1 %}
            <h4 class='cred'> {{ error1 }} !</h4>  
        {% endif %}
        <input  type="password" name="password1" placeholder="Password" value={{password}}> <br>
        {% if error2 %}
            <h4 class='cred'> {{ error2 }} !</h4>  
        {% endif %}
        <input  type="password" name="password2" placeholder="Confirm Password" value={{password}}>
        <button type="submit">Submit</button>
        <span>Have one? <a href="{% url 'login' %}">Login</a> </span>
    </form>
    
</div>
{% endblock %}

RecommendationSystem/profileapp/templates/profileapp/edit_profile.html
{% extends 'base.html' %}
{% load static %}
{% block page_title %}Profile{% endblock  %}

{% block other_css_link %}
    <link rel="stylesheet" href="{% static "profileapp/edit_profile.css" %}?{% now "U" %}">
{% endblock %}

{% block page_content %}

    <div class="container">
        <form action="/profile/edit" class="form" method="post" enctype="multipart/form-data" >
            {% csrf_token %}
            <h2>User Name: {{user.username}}</h2>
            <label for="id_first_name" class="first_name">First Name: </label>
            <input required id="id_first_name" name="first_name" type="text" value={{profile.first_name}} > <br>
           
            <label for="id_last_name" class="last_name">Last Name: </label>
            <input required id="id_last_name" name="last_name" type="text" value={{profile.last_name}} > <br>
            <label for="id_gender" class="gender">Gender: </label>
            <select class"gender" required id="id_gender" name="gender">
                <option value="Male">Male</option>
                <option value="Female">Female</option>
              </select> <br>
            <label for="id_age" class="age">Age: </label>
            <input required id="id_age" name="age" type="number" value={{profile.age}} > <br>
            <label for="image" class="image">Image: </label>
            <input type="file" id="image" name="image"> <br>
            
            <button type="submit">Submit</button>
            
        </form>
    </div>

{% endblock  %}

RecommendationSystem/profileapp/templates/profileapp/profile.html
{% extends 'base.html' %}
{% load static %}
{% block page_title %}Profile{% endblock  %}

{% block other_css_link %}
    <link rel="stylesheet" href="{% static "profileapp/profile.css" %}?{% now "U" %}">
{% endblock %}

{% block page_content %}

    <div class="container">
        <div class="profile_picture">
            <img src="{{profile.profile_picture.url}}" />
        </div>
        <div class="profile_details">
            <h2>User Name: {{user.username}}</h2>
            <h2>First Name: {{profile.first_name}}</h2>
            <h2>Last Name: {{profile.last_name}}</h2>
            <h2>Gender: {{profile.gender}}</h2>
            <h2>Age: {{profile.age}}</h2> <br>
            <a class="btn button" href="/profile/edit">Edit</a> 
        </div>
    </div>

{% endblock  %}

RecommendationSystem/recommendationapp/templates/recommendationapp/aboutus.html
{% extends "base.html" %}
{% load static %}
{% block page_title %}
    About the Devs
{% endblock %}

{% block other_css_link %}
    <link rel="stylesheet" type="text/css" href="{% static "recommendationapp/aboutus3.css" %}?{% now "U" %}">
{%endblock%}

{% block nav_section %}
    {% include "nav.html"%}
{% endblock %}


{% block page_content %}
    <div class="company-details">
        <h2>Developer details</h2>
        <p>Name : Md Oshim</p>
        <p>Email : mdoshim5@gmail.com</p>
        <p>Phone : 015133846</p>
    </div>
{% endblock %}

RecommendationSystem/recommendationapp/templates/recommendationapp/allpackages.html
{% extends "base.html" %}
{% load static %}

{% block page_title %}
    All the package details
{% endblock %}

{% block other_css_link %}
    <link rel="stylesheet" href="{% static "recommendationapp/allpackages2.css" %}?{% now "U" %}">
{%endblock%}

{% block nav_section %}
    {% include "nav.html"%}
{% endblock %}


{% block page_content %}
<div class="all-package-container">
    {% for package_details in database%}
    <div class="package-container">
        <h2>Package: {{package_details.package}}</h2>
        <hr>
        <h4>VCPU : {{package_details.vcpu}}</h4>
        <h4>RAM : {{package_details.ram}}</h4>
        <h4>Storage Type : {{package_details.storage_type}}</h4>
        <h4>Storage Amount : {{package_details.storage_amount}}</h4>
        <h4>Network Bandwidth : {{package_details.network_bandwidth}} Gbps</h4>
        <h4>Processor: {{package_details.processor}}</h4>
    </div>
    {% endfor %}
</div>
{% endblock %}

RecommendationSystem/recommendationapp/templates/recommendationapp/choseoptions.html
{% extends "base.html" %}
{% load static %}
{% block page_title %}
    Chose your choice of offering data
{% endblock %}

{% block other_css_link %}
    <link rel="stylesheet" href="{% static "recommendationapp/choseoptions3.css" %}?{% now "U" %}">
{%endblock%}

{% block nav_section %}
    {% include "nav.html"%}
{% endblock %}


{% block page_content %}
    <div class = "options-div">
        <a href="know-my-requirements" class = "option-link">I know my requirements</a>
        <a href="don't-know-my-requirements" class = "option-link">I don't know my requirements</a>
    </div>
{% endblock %}

RecommendationSystem/recommendationapp/templates/recommendationapp/dontknowmyrequirements.html
{% extends "base.html" %}
{% load static %}
{% block page_title %}
    Fill up the form to get recommendation
{% endblock %}

{% block other_css_link %}
    <link rel="stylesheet" href="{% static "recommendationapp/dontknowmyrequirements3.css" %}?{% now "U" %}">
{%endblock%}

{% block nav_section %}
    {% include "nav.html"%}
{% endblock %}


{% block page_content %}
    <div class="container">
        <form class="form" action = "" method="post">
            {% csrf_token %}
            <label for="company_size">How big is your company:</label>
            <select name="company_size" id="company_size">
                <option value="2">Small</option>
                <option value="5">Medium</option>
                <option value="10">Large</option>
                <option value="20">Extra-large</option>
            </select><br>
            <label for="expected_hits">Expected hits to System:</label>
            <select name="hits" id="hits">
                <option value="2">2 M</option>
                <option value="4">4 M</option>
                <option value="10">10 M</option>
                <option value="30">30 M</option>
            </select>
            <button class="btn" type="submit">Submit</button>
        </form>
    </div>
{% endblock %}

RecommendationSystem/recommendationapp/templates/recommendationapp/dontknowreply.html
{% extends "base.html" %}
{% load static %}
{% block page_title %}
    Recommended Package
{% endblock %}

{% block other_css_link %}
    <link rel="stylesheet" href="{% static "recommendationapp/dkr.css" %}?{% now "U" %}">
{%endblock%}

{% block nav_section %}
    {% include "nav.html"%}
{% endblock %}


{% block page_content %}
<div class="package-container">
    <h2>Package: {{package_details.package}}</h2>
    <hr>
    <h4>VCPU : {{package_details.vcpu}}</h4>
    <h4>RAM : {{package_details.ram}}</h4>
    <h4>Storage Type : {{package_details.storage_type}}</h4>
    <h4>Storage Amount : {{package_details.storage_amount}}</h4>
    <h4>Network Bandwidth : {{package_details.network_bandwidth}} Gbps</h4>
    <h4>Processor: {{package_details.processor}}</h4>
</div>
{% endblock %}

RecommendationSystem/recommendationapp/templates/recommendationapp/knowmyrequirements.html
{% extends "base.html" %}
{% load static %}
{% block page_title %}
    Fill up the form to get recommendation
{% endblock %}

{% block other_css_link %}
    <link rel="stylesheet" href="{% static "recommendationapp/kmr2.css" %}?{% now "U" %}">
{%endblock%}

{% block nav_section %}
    {% include "nav.html"%}
{% endblock %}


{% block page_content %}
    <div class="know-container">
        <h2>Choose Your Requirements</h2>
        <hr>
        <form class="form" action = "" method="post">
            {% csrf_token %}
            <label for="vcpu">Virtual-CPU: </label>
            <input required type="number" name="vcpu" id="vcpu" placeholder="How many V-CPU you want" min="2" max="128" title="min=2, max=128"><br>
            <label for="ram">RAM: </label>
            <input required type="number" name="ram" id="ram" placeholder="How much RAM you want" min="1" max="1024" title="min=1, max=1024">GB<br>
            <label for="storage_type">Storage Type:</label>
            <select name="storage_type" id="storage_type">
                <option value="1">EBS</option>
                <option value="2">NVMe SSD</option>
                <option value="3">HDD</option>
            </select><br>
            <label for="storage_amount">Storage Amount: </label>
            <input required type="number" name="storage_amount" id="storage_amount" placeholder="How much Storage you want" min="128" max="5120" title="min=128, max=5120">GB<br>
            <label for="network_bandwidth">Network Bandwidth: </label>
            <input required type="number" name="network_bandwidth" id="network_bandwidth" placeholder="How much bandwidth you want" min="25" max="100" title="min=25, max=100">Gbps<br>
            <label for="processor">Processor:</label>
            <select name="processor" id="processor">
                <option value="1">Custom Intel Xeon E5-2076 V3 haswell</option>
                <option value="2">AWS Nitro System Xeon</option>
                <option value="3">Intel Xeon pentium 8176M</option>
            </select><br>
            <button type="submit">Submit</button>
        </form>
    </div>
{% endblock %}

RecommendationSystem/recommendationapp/templates/recommendationapp/knowreply.html
{% extends "base.html" %}
{% load static %}
{% block page_title %}
    Recommended Package
{% endblock %}

{% block other_css_link %}
    <link rel="stylesheet" href="{% static "recommendationapp/dkr.css" %}?{% now "U" %}">
{%endblock%}

{% block nav_section %}
    {% include "nav.html"%}
{% endblock %}


{% block page_content %}
    <div class="package-container">
        <h2>Package: {{package_details.package}}</h2>
        <hr>
        <h4>VCPU : {{package_details.vcpu}}</h4>
        <h4>RAM : {{package_details.ram}}</h4>
        <h4>Storage Type : {{package_details.storage_type}}</h4>
        <h4>Storage Amount : {{package_details.storage_amount}}</h4>
        <h4>Network Bandwidth : {{package_details.network_bandwidth}} Gbps</h4>
        <h4>Processor: {{package_details.processor}}</h4>
    </div>
{% endblock %}

RecommendationSystem/recommendationapp/templates/recommendationapp/login2.html
{% extends "base.html" %}
{% load static %}

{% block page_title %}
    Login
{% endblock %}

{% block other_css_link %}
    <link rel="stylesheet" href="{% static "recommendationapp/login2.css" %}?{% now "U" %}">
{% endblock %}

{% block page_content %}
    <div class="container">
        <h3>Login</h3>
        <form action="/accounts/login/" class="form" method="post">
            {% csrf_token %}
            <label for="id_username" class="username">Username</label>
            <input id="id_username" name="username" type="text"> <br>
            <label for="id_password" class="password" >Password </label>
            <input id="id_password" name="password" type="password"> <br>
            <button type="submit">Submit</button>
            <span>Haven't created one? <a href="/accounts/signup">Create One</a> </span>
        </form>
    </div>

{% endblock %}

RecommendationSystem/recommendationapp/templates/recommendationapp/recommendationapp.html
{% extends "base.html" %}

{% block page_title %}
    Welcome to - Power of AI 
{% endblock %}

{% block nav_section %}
    {% include "nav.html"%}
{% endblock %}

{% block page_content %}
    <div class="content">
        <div class="middle">
            <h1>Tired of searching for suggestions for your system?</h1> <br>
            <h3>Let our AI guide you!</h3>
            <a href="/choseoptions" class="inline-block btn">Get Suggestion</a>
        </div>
    </div>
{% endblock %}

RecommendationSystem/recommendationapp/templates/recommendationapp/register.html
{% extends "base.html" %}
{% load static %}
{% block page_title %}
    Create an account
{% endblock %}

{% block other_css_link %}
    <link rel="stylesheet" href="{% static "recommendationapp/register.css" %}?{% now "U" %}">
{%endblock%}

{% block page_content %}
<div class="container">
    <h3>Create Account</h3>
    <form action="/admin/auth/user/add/" class="form" method="post">
        {% csrf_token %}
        <input type="text" name="first_name" placeholder="First Name"> <br>
        <input type="text" name="last_name" placeholder="Last Name"> <br>
        <input type="text" id="id_username" name="username" placeholder="Email or Phone"> <br>
        <input  type="password" id="id_password1" name="password1" placeholder="Password"> <br>
        <input  type="password" id="id_password2" name="password2" placeholder="Confirm Password">
        <button type="submit" value="Save" name="_save">Submit</button>
        <span>Have one? <a href="/login">Login</a> </span>
    </form>
    
</div>
{% endblock %}

RecommendationSystem/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block page_title %}{% endblock %}</title>
    <link rel="shortcut icon" href="{% static "favicon.ico" %}" type="image/x-icon">
    <link rel="icon" href="{% static "favicon.ico" %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static "base.css" %}?{% now "U" %}">
    {% block other_css_link %}{% endblock %}
</head>
<body>
    <div class="header-container">
        <header class="header">
            <a class="logo" href="/"><img height="80px" width="auto" src="{% static "official_logo.png" %}" alt="official logo"></a>
           <h1 class="title">Recommendations with power of AI</h1>
        </header>
    </div>
    <nav class= "nav">
        <div class="nav-links">
            <a href="/">Home</a>
            <a href="/allpackages">All Packages</a>
            <a href="/aboutus">About-me</a>
        </div>
        {% block nav_section %}
            {% include "nav.html"%}
        {% endblock %}        
    </nav>

    <div class="content">
        {% block page_content %} Page wise contents goes here {% endblock %}
    </div>


    <footer>
        <h3 class="center">Copyright &copy; to Md Oshim</h3>
    </footer>




</body>
</html>

RecommendationSystem/templates/loggedinnav.html
<div class="auth">
    <a href="{% url 'profile' %}">Hi {{user.username}}</a>
    <a href="{% url 'logout' %}">Logout</a>
</div>

RecommendationSystem/templates/nav.html
{% if user.is_authenticated %}
    {% include "loggedinnav.html"%}
{% else %}
    <div class="auth">
        <a href=" {% url 'login' %} ">Login</a>
        <a href=" {% url 'signup' %} ">Sign Up</a>
    </div>
{% endif %}